server:
  port: 8078

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nisum-usuario
          uri: http://localhost:8083
          predicates:
            - Path=/api/client/**